### ISSUE TITLE
Broken Hyperlink in Blog Post

### ISSUE THREAD

**Issue by MrJarnould** [SamEdwardes/samedwardes.com#50]
## Description
The blog post titled [_How to use 1Password for Secrets in ~/.bashrc or ~/.zshrc_](https://samedwardes.com/blog/2023-11-03-1password-for-secret-dotfiles/) contains a broken link to the updated post [_How to use 1Password for Secrets in ~/.bashrc or ~/.zshrc (UPDATE)_](https://samedwardes.com/blog/2023-11-28-1password-for-secret-dotfiles-update/).

## Details
- **Broken Link URL**: `https://samedwardes.com/blog/2023-11-28-1password-for-secret-dotfiles-update/index.md`
- **Expected URL**: `https://samedwardes.com/blog/2023-11-28-1password-for-secret-dotfiles-update/`

## Steps to Reproduce
1. Visit the [blog post](https://samedwardes.com/blog/2023-11-03-1password-for-secret-dotfiles/).
2. Click the link under the "Update" section.
3. Observe the 404 error page.

## Screenshots
1. **Blog Post with Broken Link**:
   ![Blog Post Screenshot](https://github.com/SamEdwardes/samedwardes.com/assets/25063422/aa54a0b5-651b-493f-9ae2-5d1d85ee2475)
   
2. **404 Error Page**:
   ![404 Error Screenshot](https://github.com/SamEdwardes/samedwardes.com/assets/25063422/ddd22e06-ab37-4c9c-becc-456870b5f1fa)
   
3. **Corrected Blog Post**:
   ![Correct Link Screenshot](https://github.com/SamEdwardes/samedwardes.com/assets/25063422/a182ffab-b416-415b-83a2-a3143139d62a)

Thank you for your informative blog posts. They have been very helpful!

**Comment by SamEdwardes** [comment]
Thank you for reporting! I just migrated from Docusauras to Astro for my blog so I must have missed some links :)

**Comment by SamEdwardes** [comment]
One solution: https://github.com/vernak2539/astro-rehype-relative-markdown-links

**Comment by SamEdwardes** [comment]
Solution: I used some regex `\[.*\]\(.*.md\)` to find all of the links that used relative file paths and updated them to work for Astro.

**Comment by MrJarnould** [comment]
I just tested – I confirm that the link works!
